name: packaging-and-releasing
on:
  pull_request:
    types:
      - closed
    branches:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  packaging-and-releasing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Edit version
        run: sed -r -i 's/(.*)(version=.*)([0-9]+).([0-9]+).([0-9]+)(.*)/echo "\1\2\3.\4.$((\5+1))\6"/ge' setup.py

      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/1.0.0/protection
          repository: ${{ github.repository }}
          required_status_checks: |
            null
          enforce_admins: |
            null
          required_pull_request_reviews: |
            null
          restrictions: | 
            null
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_ADMIN_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ github.base_ref }}
          default_author: github_actions
          message: 'Incrementing patch version in setup.py'
          add: 'setup.py'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Branch protection ON
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/1.0.0/protection
          repository: ${{ github.repository }}
          mediaType: |
            previews: 
              - luke-cage
          required_status_checks: |
            strict: true
            contexts:
              - build
          enforce_admins: |
            null
          required_pull_request_reviews: |
            dismiss_stale_reviews: true
            required_approving_review_count: 1
          restrictions: |
            null
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_REPO_ADMIN_TOKEN }}

      - name: Display setup.py
        run: cat setup.py

      - name: Install build
        run: python3 -m pip install --upgrade build

      - name: Build package
        run: python3 -m build

      - name: Release package
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
