name: packaging-and-releasing
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  packaging-and-releasing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Edit version
        run: sed -r -i 's/(.*)(version=.*)([0-9]+).([0-9]+).([0-9]+)(.*)/echo "\1\2\3.\4.$((\5+1))\6"/ge' setup.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Incrementing patch version in setup.py'
          add: 'setup.py'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Display setup.py
        run: cat setup.py

      - name: Install build
        run: python3 -m pip install --upgrade build

      - name: Build package
        run: python3 -m build

      - name: Release package
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
