name: testing
on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: pip install .[test]
      - run: python -m unittest discover skillcorner/tests/
